### ISSUE TITLE
just to share a reworked demo with JSON-based structure and lazyloading

### ISSUE THREAD

**Issue by englishextra** [ericleong/zoomwall.js#11]
It's a reworked demo of [ericleong/zoomwall.js](https://github.com/ericleong/zoomwall.js), and it is in aid of helping
the webdevs to understand the caveats when preparing the structure and logic of your front-end for production.

- Added JSON-based generating of the gallery markup
- Added lazyloading with [toddmotto/echo](https://github.com/toddmotto/echo)
- Changed initial image source with SVG placeholder
- Works in IE11 (with fetch/Promise polyfills), Edge 13  (with fetch polyfill), Chrome, Opera, Firefox

[englishextra/zoomwall.js](https://github.com/englishextra/zoomwall.js)

**Comment by ericleong** [comment]
Thanks for linking to your work! I think nowadays with [lazy loading in the browser](https://developer.mozilla.org/en-US/docs/Web/Performance/Lazy_loading), it's better to keep this library small and have the browser do the heavy lifting. JSON-based markup generation is pretty cool too but I think makes more sense in the scope of infinite scrolling, which I think this library could support better, but the loading itself is perhaps outside the scope of this library.
