### ISSUE TITLE
Next/prev Buttons

### ISSUE THREAD

**Issue by janstieler** [ericleong/zoomwall.js#5]
Hi,
is there a way to add next and prev buttons btw. how can I call the next/prev function?

Cheers

**Comment by ericleong** [comment]
Yup, like this:

```javascript
// previous
zoomwall.page(document.getElementById('gallery'), false);
// next
zoomwall.page(document.getElementById('gallery'), true);
```

**Comment by janstieler** [comment]
Hi,
no this is not directly what I mean.
```
zoomwall.page(document.getElementById('gallery'), true);
```
Makes it possible to use the keyboard, but there is no visual items for it.
What I mean, is if I add buttons on the lightbox how can I make them work with zoomwall.js?

**Comment by ericleong** [comment]
If you run that command after viewing an image in lightbox mode, it will advance to the next photo. If you look at [the keyboard code](https://github.com/ericleong/zoomwall.js/blob/master/zoomwall.js#L70-L80), it simply runs the same code.
