### ISSUE TITLE
Keys are not working while loading multiple zoomwall

### ISSUE THREAD

**Issue by maulinpandya2006** [ericleong/zoomwall.js#8]
Hi,

I like your ZoomWall plugin and your creativity. Its good to see such innovative gallery style.

I have implemented this zoomwall plugin in one of my project. I have many photo albums and on click of each I have called ajax method for loaded respective album images. 

On successful data loading, I have called your plugin using "zoomwall.create(document.getElementById('zoomwall'), true)". Its perfectly working when I open a album on  first time of page load but when i click on second album zoomwall keys (image next/back function using keyboard arrows) support is not working.  

I have also tired to adding "zoomwall.keys()" on ajax data loading success but still not working.

I request you kindly check this issue as soon as possible as i have already implemented your excellent plugin and need to sort out this issue.  

Great Work !,

Thanks,
Maulin

**Comment by ericleong** [comment]
It seems that you need to defocus the first album when the user clicks on the second album - you can do this by storing the returned object from `zoomwall.keys()`, like this:

```js
var firstGalleryListener = zoomwall.keys(document.getElementById('first_gallery'));

// do this when the user clicks on the second album
document.removeEventListener('keydown', firstGalleryListener);
var secondGalleryListener = zoomwall.keys(document.getElementById('second_gallery'));
```

**Comment by maulinpandya2006** [comment]
Thanks Eric. I did the same and working great. You Rocks....

**Comment by maulinpandya2006** [comment]
Hi Eric, 

Is it possible to make this plugin compatible with Internet explore 9 and 10.
Kindly let me know.

Thanks,
Maulin

**Comment by ericleong** [comment]
Sorry, I don't have access to a computer that runs Internet Explorer 9 or 10.
