### ISSUE TITLE
Zoom not working

### ISSUE THREAD

**Issue by fusteel** [ericleong/zoomwall.js#9]
First of all i'm not much of a javascript pro so I can't seem to resolve this without contacting you. I can't seem to get the zoom to work. The images are placed perfectly but nothing happens when i click them. Is there something I am doing wrong?
![screen shot 2016-05-30 at 2 35 25 pm](https://cloud.githubusercontent.com/assets/18401413/15656301/c31ace5e-2673-11e6-988c-5d08425c0fb3.png) @ericleong

**Comment by ericleong** [comment]
Either use `window.onload` or `$(document).ready();`, but not both.

So I would recommend changing it to

```javascript
$(document).ready(function() {
  zoomwall.create(document.getElementById('gallery'));
});
```
